Ready to review
MaxHlystov/my_android_card pull request #3
Opened 2018-09-27 09:19 UTC by MaxHlystov

2018-09-27 20:03 UTC, PStrelchenko requested changes
Нужны правки. Но стало гораздо лучше!

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/BrowserOpener.java
> +    static public void openURL(@NonNull Activity activity, @NonNull String url) {
В Java обычно сначала идет модификатор доступа, а затем уже признак того, статический ли метод, или нет. То есть:

public static void openUrl.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/BrowserOpener.java
> +        intent.setData(Uri.parse(url));
А здесь не нужна проверка на возможность открытия Intent-а?

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +        if(config == null)
Лучше поставь фигурные скобочки в if-е + после if-а поставь пробел. То есть:

if (config == null) {
   // ...
}

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +    private ConfigValues() {}
Конструктор класса обычно пишут ДО всех других методов. Как и поля класса.
То есть структура обычного класса в Java:

1) статические поля
2) обычные поля
3) статические методы
4) конструктор
5) override методы
6) обычные методы

Я долго искал глазами, а где же переменная для твоего синглтона =)))

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +    public static IConfigValues getConfig() {
Я бы еще пометил метод как @NonNull

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +    public String getURL_Telegram() {
В Java названия методов обычно пишутся без нижнего подчеркивания. Разве что названия тестов, но у нас здесь не тот случай.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/IConfigValues.java
> +    String getMyEmail();
Я бы пометил каждый метод аннотацией @NonNull

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        ImageView img_telegram = findViewById(R.id.telega);
Переменные в Java тоже обычно пишутся без нижних подчеркиваний. 
Названия пакетов - ок, названия тестов - ок. Но переменные и методы, обычно, пишутся без нижних подчеркиваний.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +            @Nullable Intent i = getMailIntent(config.getMyEmail(), getString(R.string.greeting), tv_msg.getText().toString());
Возле переменных очень редко указывают аннотации.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +            @Nullable Intent i = getMailIntent(config.getMyEmail(), getString(R.string.greeting), tv_msg.getText().toString());
Плюс - я все-таки за более-менее осмысленные имена переменных. 
i - не очень хорошее название для переменной. 
intent - лучше.
mailIntent - еще лучше.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +        return "https://linkedin.com/pub/maxim-khlystov/a7/6ba/123";
У тебя здесь явно имеется какое-то перечисление (enum) с одинаковым свойством url. Я прям настоятельно бы рекомендовал завести enum для всех твоих констант, кроме email-а. Назвал бы его SocialNetwork:

```
enum SocialNetwork {

     TELEGRAM("..."),
     LINKED_IN("..."),
     GITHUB("..");

     @NonNull
     private final String url;

     SocialNetwork(@NonNull String url) {
         this.url = url;
     }

     @NonNull
     public String getUrl() {
          return url;
      }
}
```

А потом бы использовал здесь:

```
@Override
@NonNull
public String getGithubUrl() {
    return SocialNetwork.GITHUB.getUrl();
}
```

Что тебе это даст - это даст адекватную группировку твоих констант в одном месте с некоторым неабстрактным контекстом (это теперь не просто строчка текста, а именно строчка, относящаяся к социальной сети) + все плюшки enum-а. Итерирование, подсказки линта в switch-ах.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable TextView addTextView(@NonNull Activity activity,
Аннотации на метод обычно размещают над самим методом:
```
@Nullable
private TextView addTextView
```

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        return tv;
Вопрос - а зачем ты возвращаешь из метода TextView, если он у тебя нигде не используется? И почему он @Nullable, если ты всегда возвращаешь @NonNull?

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable Intent getMailIntent(@NonNull String to,
Аннотации на метод обычно помещают над названием метода:

```
@Nullable
private Intent getMailIntent ...
```

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        String mailto = "mailto:" + to + "?subject=" + subject + "&body=" + msg;
Эта штука не так задается. 
https://developer.android.com/guide/components/intents-common#Email

Ты не должен формировать строчку с subject и body. Для этого есть специальные параметры Intent-а: 

```
Intent intent = new Intent(Intent.ACTION_SENDTO);
    intent.setData(Uri.parse("mailto:")); // only email apps should handle this
    intent.putExtra(Intent.EXTRA_EMAIL, addresses);
    intent.putExtra(Intent.EXTRA_SUBJECT, subject);
    intent.putExtra(Intent.EXTRA_TEXT, body)
```

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        if (i.resolveActivity(getPackageManager()) != null)
Не забывай добавлять фигурные скобочки для if-блоков. Даже если там только 1 выражение.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable Intent getMailIntent(@NonNull String to,
Очень похоже, что метод `getMailIntent` можно засунуть в какой-нибудь утилитный класс, например IntentUtils, чтобы "почистить" activity.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable Intent getMailIntent(@NonNull String to,
В этот же IntentUtils можно засунуть и код генерации Intent-а для открытия URL через браузер. По мне это будет гораздо лучше, чем не очень понятный класс `BrowserOpener`.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/res/layout-land/activity_main.xml
> +        android:layout_toRightOf="@id/my_photo">
По идее, Android Studio должна была просигналить тебе, что тебе нужно здесь писать `layout_toEndOf`, а не `layout_toRightOf`, ведь у тебя minSDK = 21.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/res/layout/content.xml
> +        <LinearLayout
Я вроде уже писал, что LinearLayout, который содержит в себе иконку и TextView, можно заменить на TextView с compoundDrawable. Замени, пожалуйста. Разметка станет сразу проще.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/res/values-ru/strings.xml
> +    <string name="NoEmail">Не найдена почтовая программа</string>
id в ресурсах, обычно, делают в lower_snake_case-е. 
Придерживайся одного стиля именования всех ресурсов - либо все в lower_snake, либо все в camelCase. Не надо смешивать.

2018-09-27 20:03 UTC, PStrelchenko commented on app/src/main/res/layout-sw600dp-land/activity_main.xml
> +    <RelativeLayout
Зачем здесь дополнительный RelativeLayout в качестве обертки над ScrollView? 
Это дополнительный уровень вложенности, нужно от этого стараться избавляться. 

Насколько знаю, к include-у можно применять аттрибуты linear layout-а спокойно.

2018-09-27 20:03 UTC, PStrelchenkoHH commented on app/src/main/res/layout-sw600dp-land/activity_main.xml
> +    <ImageView
У тебя опять фотографии не отображаются так, как требовалось в задании. В задании требовалось, чтобы фотография занимала всю ширину экрана. На горизонтальной верстке - всю высоту экрана.
Посмотри, почитай про аттрибут `scaleType`.

2018-09-27 21:16 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +            @Nullable Intent i = getMailIntent(config.getMyEmail(), getString(R.string.greeting), tv_msg.getText().toString());
Тут не соглашусь. Если область видимости переменной очень маленькая, то можно и i поставить. Читаемость это не уменьшит.

2018-09-27 21:30 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        String mailto = "mailto:" + to + "?subject=" + subject + "&body=" + msg;
Кто-то из менторов рекомендовал эту статью https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f
С putExtra у меня не работало. Так как сейчас сделано заработало.

2018-09-27 21:34 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable Intent getMailIntent(@NonNull String to,
Меня пугает желание поместить что-нибудь в класс или модуль что-нибудьUtils. Потому что эта штука потом превращается в помойку, и требуются значительные усилия, чтобы ее разгрести. По крайней мере в моем опыте это происходило неоднократно.

2018-09-27 21:34 UTC, MaxHlystov commented on app/src/main/res/layout/content.xml
> +        <LinearLayout
Пропустил :(

2018-09-27 21:40 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        return tv;
Это привычка закладываться на будущее. Переписывать код сложнее, чем его переиспользовать. Если я возвращаю, что-то, это потом можно как-то дополнительно обработать. Иначе, придется создавать копию функции: !DRY. Если в Java компилятор не может отследить, что возвращать ничего не нужно и оптимизировать вызов, то я уберу возвращаемое значение.

2018-09-27 21:42 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +        return "https://linkedin.com/pub/maxim-khlystov/a7/6ba/123";
Я сделаю как ты сказал, но я не согласен. Для меня enum-ы - это часть DSL. А ссылки на мои соц. сети едва-ли тянут по важности на включение в качестве ключевых слов, пусть даже в игрушечный язык.

2018-09-27 21:44 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ConfigValues.java
> +        return "https://linkedin.com/pub/maxim-khlystov/a7/6ba/123";
Тут пригодилось бы чтение конфигов, но я еще не нашел времени разобраться как в Андроид принято с ними работать.

2018-09-27 21:48 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        ImageView img_telegram = findViewById(R.id.telega);
Наверное я неправильно понял правило именования вьюх отсюда https://github.com/RedMadRobot/kotlin-style-guide#naming
У меня логика следующая: имя переменной однозначно соответствует id в xml.

2018-09-27 22:26 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        ImageView img_telegram = findViewById(R.id.telega);
Я понял логику, в целом, ты прав. 
Но их style guide, все же, про Kotlin и про использование Kotlin Android extensions, где можно по id вьюхи сразу работать со View. Поэтому у них в коде и разрешают писать lower_snake_ имена, но это как бы именно идентификаторы.
Отсюда и когнитивный диссонанс =) 
А у тебя - переменная img_telegram. Это не id вьюхи. И переменные, обычно, пишут в camelCase.

2018-09-27 22:26 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +            @Nullable Intent i = getMailIntent(config.getMyEmail(), getString(R.string.greeting), tv_msg.getText().toString());
Ок =) Это вопрос из разряда "вкусовщины", соглашусь тут с тобой.

2018-09-27 22:27 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        return tv;
Ок =) В чем-то ты прав здесь.

2018-09-27 22:27 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +        String mailto = "mailto:" + to + "?subject=" + subject + "&body=" + msg;
Здесь мой косяк, что не проверил. Ок.

2018-09-27 22:35 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MainActivity.java
> +    private @Nullable Intent getMailIntent(@NonNull String to,
Согласен, что со временем Utils превращается в помойку. 
Но для этого и нужно код ревью. Чтобы другие участники команды могли тебе сказать, что что-то не так. В плане, что они могут увидеть, как ты (или кто-то еще из команды) добавляешь какую-то постороннюю штуку в утилитный класс, предназначенный для определенных целей.

По поводу конкретно данного кейса: можно назвать класс ThirdPartyIntentInteractor, и считать, что класс предназначен строго для построения Intent-ов, открывающих какие-то другие приложения: приложение для СМС, для email, для звонков и тп, и тд =)

2018-09-28 17:26 UTC, MaxHlystov commented on app/src/main/res/layout/content.xml
> +        <LinearLayout
Через compound получается плохо. Проблемы с выравниванием картинки и текста. Проблема с установкой отступов между картинкой и текстом. Буду делать через customView.

2018-09-29 12:13 UTC, PStrelchenko approved these changes
Можно продолжать работу, остались только мелкие замечания. Их можно поправить позже.

2018-09-29 12:13 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ImagedTextView.java
> +        this.context = context;
Когда ты наследуешься от View, не нужно запоминать в полях Context. Потому что у View уже есть такое свойство, его можно достать через `getContext()`.

2018-09-29 12:13 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ImagedTextView.java
> +        this.context = context;
Здесь, соответственно, тоже не нужно это присваивание.

2018-09-29 12:13 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ImagedTextView.java
> +    public ImagedTextView(@NonNull Context context) {
Обычно, когда ты делаешь custom view, переопределяют конструкторы так, чтобы они вызывали друг друга:

```
public ImagedTextView(@NonNull Context context) {
    this(context, null);
}

public ImagedTextView(@NonNull Context context, @Nullable AttributeSet attrs) {
    this(context, attrs, 0);
}

public ImagedTextView(@NonNull Context context, @NonNull AttributeSet attrs, int defStyleAttr) {
    super(context, attrs, defStyleAttr);
}
```

2018-09-29 12:13 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ImagedTextView.java
> +        TypedArray typedArray = context.getTheme().obtainStyledAttributes(
Получение typedArray обычно засовывают в try-catch:
+ не обязательно получать obtainStyledAttributes через getTheme - можно напрямую. 
```
TypedArray typedArray = null;
try {
    typedArray = context.obtainStyledAttributes( .. )
} catch {
    if (typedArray != null) {
        typedArray.recycle();
    }
}
```

Особой причины так делать нет - насколько знаю, obtainStyledAttributes не бросает исключений. Но в коде я чаще вижу всю работу с typedArray внутри try-catch.

2018-09-29 12:13 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/ImagedTextView.java
> +        if (text == null || text.isEmpty()) {
text == null || text.isEmpty --> можно заменить на android.text.TextUtils.isEmpty(text)

2018-09-29 12:13 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/myportfolio/MailIntent.java
> +public class MailIntent {
Может, все-таки, объединить классы BrowserIntent и MailIntent в `ThirdPartyIntentUtils`?

2018-09-30 09:07 UTC, merged